### ISSUE TITLE
Cannot open Preferences for input methods

### ISSUE THREAD

**Issue by kdwk** [Vanilla-OS/gnome-control-center#17]
# Problem
The preferences window for ibus input methods cannot be opened.

# Steps to reproduce
1. Add the ibus Chinese Pinyin input method
2. Try to open Preferences from Settings -> Keyboard

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/213848857-3d912fd1-004e-4829-99ee-3a1906cc3abd.png)

It works here. Do you have some more details or useful info to replicate?

**Comment by mirkobrombin** [comment]
Can you start gnome-control-center from your terminal and post the latest 20 lines?

**Comment by kdwk** [comment]
`/.system/usr/share/ibus-pinyin/setup/main.py:31: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/.system/usr/share/ibus-pinyin/setup/main.py:32: PyGIWarning: IBus was imported without specifying a version first. Use gi.require_version('IBus', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import IBus
/.system/usr/share/ibus-pinyin/setup/main.py:44: DeprecationWarning: bind_textdomain_codeset() is deprecated
  gettext.bind_textdomain_codeset("ibus-pinyin", "UTF-8")
Traceback (most recent call last):
  File "/.system/usr/share/ibus-pinyin/setup/main.py", line 428, in <module>
    main()
  File "/.system/usr/share/ibus-pinyin/setup/main.py", line 424, in main
    PreferencesDialog(name).run()
  File "/.system/usr/share/ibus-pinyin/setup/main.py", line 50, in __init__
    self.__builder.add_from_file("ibus-pinyin-preferences.ui")
gi.repository.GLib.GError: gtk-builder-error-quark: ibus-pinyin-preferences`
